package http;

import http.api.RequestHandlers;
import rawhttp.core.RawHttp;
import rawhttp.core.body.StringBody;
import rawhttp.core.server.TcpRawHttpServer;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.Optional;

/**
 * This class is the example source used to generate a HTTP server from the annotations
 * declared in the annotations module.
 * <p>
 * The real runtime class will be generated by the HttpAnnotationProcessor.
 */
public final class HttpServer {
    private final RawHttp http = new RawHttp();
    private final TcpRawHttpServer server;

    public HttpServer( int port ) {
        this.server = new TcpRawHttpServer( port );
    }

    public void run( RequestHandlers handlers ) {
        server.start( ( req ) -> {
            String body = null;
            var path = req.getUri().getPath();
            if ( req.getMethod().equals( "GET" ) ) {
                var h = handlers.getGetHandlers().get( path );
                if ( h != null ) {
                    body = h.get();
                }
            } else if ( req.getMethod().equals( "POST" ) ) {
                var h = handlers.getPostHandlers().get( path );
                if ( h != null ) {
                    var reqBody = req.getBody().map(
                            b -> {
                                try {
                                    return b.decodeBodyToString( StandardCharsets.UTF_8 );
                                } catch ( IOException e ) {
                                    throw new RuntimeException( e );
                                }
                            } ).orElse( "" );
                    body = h.apply( reqBody );
                }
            }
            if ( body == null ) {
                return Optional.empty();
            }
            return Optional.of( http.parseResponse( "200 OK" )
                    .withBody( new StringBody( body, "text/plain" ) ) );
        } );
    }

}
